spring:
  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
