# application.yml

spring:
  profiles:
    active: prod
  application:
    name: email-serviceMM

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  aliyun-access-key: LTAIzeljtTXgtY6p
  aliyun-access-secret: dJkHgfbvwFGfxoPpXW4z2YeI7XmJQP
